version: 0.2

env:

phases:
  install:
    commands:
      - echo "Hello world" > target.txt 
    finally:
  pre_build:
  build:
    commands:
    finally:
  post_build:
    commands:
artifacts:
  files:
    - target.txt 
